### ISSUE TITLE
ERROR when starting

### ISSUE THREAD

**Issue by devilAPI** [YouthGamer/discord-bot-dashboard#4]
[nodemon] starting `node discord-bot-sourcefiles/main.js`
internal/modules/cjs/loader.js:1170
    throw err;
    ^

SyntaxError: C:\Users\Felix Seiboldt\Documents\discord-bot-dashboard-master\private_config.json: Unexpected token / in JSON at position 0
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1167:22)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Felix Seiboldt\Documents\discord-bot-dashboard-master\discord-bot-sourcefiles\main.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)

**Comment by creatort** [comment]
Delete the private_config.json file & remove it from the main.js file

**Comment by devilAPI** [comment]
fixed it but now i have a chalk error

`C:\Users\Felix\Desktop\DiscordDash\api\app.js:13
const ctx = new chalk.constructor({level: 3});
            ^

TypeError: chalk.constructor is not a constructor
    at Object.<anonymous> (C:\Users\Felix\Desktop\DiscordDash\api\app.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Felix\Desktop\DiscordDash\discord-bot-sourcefiles\main.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by devilAPI** [comment]
well... i fixed it using "new chalk.instance()" instead of "new chalk.constructor()" but now it just wont start. it dosent give me an error it just says nothing. node is not crashed but its not displaying "chalk.greenBright('\n>> Bot is ready!'" in console

**Comment by devilAPI** [comment]
(node:17528) UnhandledPromiseRejectionWarning: Error: Something took too long to do.
    at C:\Users\Felix\Desktop\DiscordDash\node_modules\discord.js\src\client\ClientManager.js:40:57
    at Timeout._onTimeout (C:\Users\Felix\Desktop\DiscordDash\node_modules\discord.js\src\client\Client.js:422:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:17528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by creatort** [comment]
Sorry - I don't really know much about this project so i can't help you very well.

**Comment by devilAPI** [comment]
fixed.
